import Hardware from './Images/Hardware.jpg'
import Book from './Images/Book.jpg'
import Bakery from './Images/Bakery.jpg'
import Pharmacy from './Images/Pharmacy.jpg'
import Jewellery from './Images/Jewellery.jpg'
import Icecream from './Images/Icecream.jpg'
import Electronics from './Images/Electronics.jpg'
import Clothing from './Images/Clothing.jpg'
import Grocery from './Images/Grocery.jpg'
import Furniture from './Images/Furniture.jpg'


export const ShopList = [
    {
      id: "1",
      name: "Kumar Stores",
      email: "kumar@store.com",
      category: "Grocery",
      picture: Grocery,
      address: "123 Main St, Coimbatore",
      latitude: 11.0168,
      longitude: 76.9558,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "2",
      name: "Meena Textiles",
      email: "meena@textiles.com",
      category: "Clothing",
      picture: Clothing,
      address: "456 Market Rd, Coimbatore",
      latitude: 11.0046,
      longitude: 76.9629,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "3",
      name: "Ram Electricals",
      email: "ram@electricals.com",
      category: "Electronics",
      picture: Electronics,
      address: "789 Town Hall, Coimbatore",
      latitude: 11.0016,
      longitude: 76.9611,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "4",
      name: "Sri Krishna Bakery",
      email: "krishna@bakery.com",
      category: "Bakery",
      picture: Bakery,
      address: "123 Gandhi St, Coimbatore",
      latitude: 11.0183,
      longitude: 76.9747,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "5",
      name: "Arun Ice Creams",
      email: "arun@icecreams.com",
      category: "Ice Cream",
      picture: Icecream,
      address: "456 Park St, Coimbatore",
      latitude: 11.0207,
      longitude: 76.9436,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "6",
      name: "Ravi Books",
      email: "ravi@books.com",
      category: "Bookstore",
      picture: Book,
      address: "789 College Rd, Coimbatore",
      latitude: 11.0280,
      longitude: 76.9530,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "7",
      name: "Siva Furniture",
      email: "siva@furniture.com",
      category: "Furniture",
      picture:Furniture,
      address: "123 Race Course, Coimbatore",
      latitude: 11.0085,
      longitude: 76.9663,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "8",
      name: "Vijay Hardware",
      email: "vijay@hardware.com",
      category: "Hardware",
      picture: Hardware,
      address: "456 Cross Cut Rd, Coimbatore",
      latitude: 11.0174,
      longitude: 76.9723,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "9",
      name: "Anand Medicals",
      email: "anand@medicals.com",
      category: "Pharmacy",
      picture: Pharmacy,
      address: "789 Brookefields, Coimbatore",
      latitude: 11.0151,
      longitude: 76.9639,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "10",
      name: "Saravana Jewellers",
      email: "saravana@jewellers.com",
      category: "Jewellery",
      picture:Jewellery,
      address: "123 Gandhipuram, Coimbatore",
      latitude: 11.0223,
      longitude: 76.9488,
      createdAt: new Date(),
      updatedAt: new Date(),
    }
  ];